name: task-vectors
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - blas
  - brotlipy
  - bzip2
  - ca-certificates
  - cffi
  - cryptography
  - ffmpeg
  - freetype
  - giflib
  - gmp
  - gnutls
  - jbig
  - jpeg
  - lame
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libdeflate
  - libffi
  - libiconv
  - libpng
  - libtiff
  - libuuid
  - libwebp
  - libwebp-base
  - lz4-c
  - ncurses
  - nettle
  - numpy-base
  - openh264
  - openssl
  - pip
  - python=3.10.4
  - python_abi
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - readline
  - setuptools
  - sqlite
  - tk
  - tzdata
  - xz
  - zlib
  - zstd
  - pip:
    - certifi==2022.9.24
    - charset-normalizer==2.1.1
    - contourpy==1.0.5
    - cycler==0.11.0
    - filelock==3.8.0
    - fonttools==4.37.4
    - ftfy==6.1.1
    - huggingface-hub==0.10.0
    - idna==3.4
    - kiwisolver==1.4.4
    - matplotlib==3.6.0
    - numpy==1.26.4
    - open-clip-torch==2.0.2
    - packaging==21.3
    - pandas==1.5.0
    - patsy==0.5.2
    - pillow==9.2.0
    - plotly==5.11.0
    - pycparser==2.21
    - pyopenssl==22.0.0
    - pyparsing==3.0.9
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - pytz==2022.4
    - pyyaml==6.0
    - regex==2022.9.13
    - requests==2.28.1
    - scipy==1.9.1
    - seaborn==0.12.1
    - six==1.16.0
    - statsmodels==0.13.2
    - tenacity==8.1.0
    - torch==1.12.1
    - torchaudio==0.12.1
    - torchvision==0.13.1
    - tqdm==4.64.1
    - typing-extensions==4.3.0
    - urllib3==1.26.12
    - wcwidth==0.2.5
    - wheel==0.37.1